/* pipeline {
  agent none
  stages {
    stage('Back-end') {
      agent {
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
      }
      steps {
        sh 'mvn --version'
      }
    }
    stage('Front-end') {
      agent {
        docker { image 'node:16-alpine' }
      }
      steps {
        sh 'node --version'
      }
    }
  }
} */

pipeline {
    agent {
        docker {
            image 'maven:3.8.1-adoptopenjdk-11'
            args '-v $HOME/.m2:/root/.m2' // Mount Maven cache to speed up builds
        }
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
                sh 'pwd'
                sh 'ls -la' 
            }
        }

        stage('Build and Run') {
            steps {
                script {
            sh 'javac /var/lib/jenkins/workspace/docker-agent/multi-stage-multi-agent/Demo.java'
            sh 'java -classpath /var/lib/jenkins/workspace/docker-agent/multi-stage-multi-agent/Demo'
        }
            }
        }
    }
}

