/* pipeline {
  agent none
  stages {
    stage('Back-end') {
      agent {
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
      }
      steps {
        sh 'mvn --version'
      }
    }
    stage('Front-end') {
      agent {
        docker { image 'node:16-alpine' }
      }
      steps {
        sh 'node --version'
      }
    }
  }
} */

pipeline {
    agent {
        docker {
            image 'maven:3.8.1-adoptopenjdk-11'
           // args '-v $HOME/.m2:/root/.m2' // Mount Maven cache to speed up builds
        }
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build and Run') {
            steps {
                script {
                    // Compile Java code
                    sh 'javac Demo.java'

                    // Run the compiled Java program
                    sh 'java Demo'
                }
            }
        }
    }
}

